openapi: 3.1.0
info:
  title: SMSBOX - API Documentation
  version: 2.0.0
  contact:
    url: https://www.smsbox.net
  x-logo:
    url: "./doc/logo-en.png"
    backgroundColor: "#FFFFFF"
    altText: "SMSBOX logo"
    href: https://www.smsbox.net

servers:
  - url: http://api.smsbox.pro

tags:
  - name: whatsapp-text-and-media-messages
    x-displayName: Message
  - name: whatsapp-templates-messages
    x-displayName: Template
  - name: whatsapp-event-messages
    x-displayName: Event
  - name: whatsapp-file-messages
    x-displayName: File
  - name: whatsapp-webhooks
    x-displayName: WebHooks
x-tagGroups:
  - name: WhatsApp
    tags:
      - whatsapp-text-and-media-messages
      - whatsapp-templates-messages
      - whatsapp-event-messages
      - whatsapp-file-messages
      - whatsapp-webhooks

paths:
  /waba/json/{wabaId}/message/{phoneID} (text message):
    description: Send message
    post:
      tags:
        - whatsapp-text-and-media-messages
      security:
        - ApiKey: []
      summary: Send message
      parameters:
        - name: wabaId
          in: path
          description: WhatsApp Business Agent ID
          required: true
          schema:
            type: string
        - name: phoneID
          in: path
          description: WhatsApp Business Agent's Phone Number ID
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                recipients:
                  type: array
                  items:
                    type: string
                  maxItems: 5000
                  example:
                    - +336XXXXXXXX
                contentMessage:
                  oneOf:
                    - $ref: "./schemas/message.yaml#/Text"
                    - $ref: "./schemas/message.yaml#/Media"
                    - $ref: "./schemas/message.yaml#/Location"
      responses:
        "202":
          description: Request successfully queued.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/MessageContentResponse202"
        "400":
          description: Wrong query syntax or missing mandatory field.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/MessageContentResponse400"
        "403":
          description: Access to the requested resource has been denied.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/MessageContentResponse403"
        "404":
          description: The requested resource was not found.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/MessageContentResponse404"

        "413":
          description: The request payload exceeds the maximum allowed size.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/MessageContentResponse413"

        "503":
          description: Service temporarily unavailable.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/MessageContentResponse503"

      x-codeSamples:
        - lang: cURL
          source:
            $ref: snippets/whatsapp/message/text/snippet.sh
        - lang: Python
          source:
            $ref: snippets/whatsapp/message/text/snippet.py
        - lang: JavaScript
          source:
            $ref: snippets/whatsapp/message/text/snippet.js
        - lang: PHP
          source:
            $ref: snippets/whatsapp/message/text/snippet.php

  /waba/json/{wabaId}/message/{phoneID} (otp template message):
    post:
      tags:
        - whatsapp-templates-messages
      security:
        - ApiKey: []
      summary: Send OTP message
      parameters:
        - name: wabaId
          in: path
          description: WhatsApp Business Agent ID
          required: true
          schema:
            type: string
        - name: phoneID
          in: path
          description: WhatsApp Business Agent's Phone Number ID
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                recipients:
                  type: array
                  items:
                    type: string
                  maxItems: 5000
                  example:
                    - +336XXXXXXXX
                contentMessage:
                  $ref: "./schemas/template.yaml#/OTPTemplateMessage"
      responses:
        "202":
          description: Request successfully queued.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/MessageContentResponse202"
        "400":
          description: Wrong query syntax or missing mandatory field.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/MessageContentResponse400"
        "403":
          description: Access to the requested resource has been denied.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/MessageContentResponse403"
        "404":
          description: The requested resource was not found.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/MessageContentResponse404"

        "413":
          description: The request payload exceeds the maximum allowed size.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/MessageContentResponse413"

        "503":
          description: Service temporarily unavailable.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/MessageContentResponse503"

      x-codeSamples:
        - lang: cURL
          source:
            $ref: snippets/whatsapp/template/otp/snippet.sh
        - lang: Python
          source:
            $ref: snippets/whatsapp/template/otp/snippet.py
        - lang: JavaScript
          source:
            $ref: snippets/whatsapp/template/otp/snippet.js
        - lang: PHP
          source:
            $ref: snippets/whatsapp/template/otp/snippet.php

  /waba/json/{wabaId}/event/{phoneID}:
    post:
      tags:
        - whatsapp-event-messages
      security:
        - ApiKey: []
      summary: Send read message status
      parameters:
        - name: wabaId
          in: path
          description: WhatsApp Business Agent ID
          required: true
          schema:
            type: string
        - name: phoneID
          in: path
          description: WhatsApp Business Agent's Phone Number ID
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                $ref: "./schemas/event.yaml#/ReadEventMessage"

      responses:
        "202":
          description: Request successfully queued.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/MessageContentResponse202"
        "400":
          description: Wrong query syntax or missing mandatory field.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/MessageContentResponse400"
        "403":
          description: Access to the requested resource has been denied.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/MessageContentResponse403"
        "404":
          description: The requested resource was not found.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/MessageContentResponse404"

        "413":
          description: The request payload exceeds the maximum allowed size.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/MessageContentResponse413"

        "503":
          description: Service temporarily unavailable.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/MessageContentResponse503"

      x-codeSamples:
        - lang: cURL
          source:
            $ref: snippets/whatsapp/event/read/snippet.sh
        - lang: Python
          source:
            $ref: snippets/whatsapp/event/read/snippet.py
        - lang: JavaScript
          source:
            $ref: snippets/whatsapp/event/read/snippet.js
        - lang: PHP
          source:
            $ref: snippets/whatsapp/event/read/snippet.php

  /waba/json/{wabaId}/file/{phoneID}:
    post:
      tags:
        - whatsapp-file-messages
      security:
        - ApiKey: []
      summary: Retrieve file received in a message
      parameters:
        - name: wabaId
          in: path
          description: WhatsApp Business Agent ID
          required: true
          schema:
            type: string
        - name: phoneID
          in: path
          description: WhatsApp Business Agent's Phone Number ID
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                file_id:
                  type: string
                  description: File ID received via webhook
                  example: "1234567890"
              required:
                - file_id

      responses:
        "200":
          description: Request successfully processed.
          content:
            application/json:
              schema:
                type: object
                properties:
                  response:
                    type: object
                    properties:
                      response_code:
                        type: string
                        example: "200"
                      response_desc:
                        type: string
                        example: "Request successfully processed."
                  details:
                    type: string
                    example: Done.
                  data:
                    type: object
                    properties:
                      mime_type:
                        type: string
                        description: Mime type of the document file
                        example: application/pdf
                      sha256:
                        type: string
                        description: SHA-256 file hash
                      file_size:
                        type: string
                        description: Size in bytes
                      raw:
                        type: string
                        description: Base64 encoded file content
                        example: "data:application/pdf;base64,xxxxxxxxxxxxxxxxxx"
        "400":
          description: Wrong query syntax or missing mandatory field.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/MessageContentResponse400"
        "403":
          description: Access to the requested resource has been denied.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/MessageContentResponse403"
        "404":
          description: The requested resource was not found.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/MessageContentResponse404"

        "413":
          description: The request payload exceeds the maximum allowed size.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/MessageContentResponse413"

        "503":
          description: Service temporarily unavailable.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/MessageContentResponse503"

      x-codeSamples:
        - lang: cURL
          source:
            $ref: snippets/whatsapp/file/retrieve/snippet.sh
        - lang: Python
          source:
            $ref: snippets/whatsapp/file/retrieve/snippet.py
        - lang: JavaScript
          source:
            $ref: snippets/whatsapp/file/retrieve/snippet.js
        - lang: PHP
          source:
            $ref: snippets/whatsapp/file/retrieve/snippet.php

webhooks:
  Text:
    post:
      tags:
        - whatsapp-webhooks
      requestBody:
        content:
          application/json:
            schema:
              $ref: "./schemas/webhook.yaml#/Text"

      responses:
        "200":
          description: Return an HTTP 200 status and the word "OK" only to indicate that the data was received successfully.

  Document:
    post:
      tags:
        - whatsapp-webhooks
      requestBody:
        content:
          application/json:
            schema:
              $ref: "./schemas/webhook.yaml#/Document"
      responses:
        "200":
          description: Return an HTTP 200 status and the word "OK" only to indicate that the data was received successfully.

  Image:
    post:
      tags:
        - whatsapp-webhooks
      requestBody:
        content:
          application/json:
            schema:
              $ref: "./schemas/webhook.yaml#/Image"
      responses:
        "200":
          description: Return an HTTP 200 status and the word "OK" only to indicate that the data was received successfully.

  Video:
    post:
      tags:
        - whatsapp-webhooks
      requestBody:
        content:
          application/json:
            schema:
              $ref: "./schemas/webhook.yaml#/Video"
      responses:
        "200":
          description: Return an HTTP 200 status and the word "OK" only to indicate that the data was received successfully.

  Reaction:
    post:
      tags:
        - whatsapp-webhooks
      requestBody:
        content:
          application/json:
            schema:
              $ref: "./schemas/webhook.yaml#/Reaction"
      responses:
        "200":
          description: Return an HTTP 200 status and the word "OK" only to indicate that the data was received successfully.

  Location:
    post:
      tags:
        - whatsapp-webhooks
      requestBody:
        content:
          application/json:
            schema:
              $ref: "./schemas/webhook.yaml#/Location"
      responses:
        "200":
          description: Return an HTTP 200 status and the word "OK" only to indicate that the data was received successfully.

  MessageStatus:
    post:
      description: Message status
      tags:
        - whatsapp-webhooks
      requestBody:
        content:
          application/json:
            schema:
              $ref: "./schemas/webhook.yaml#/MessageStatus"
      responses:
        "200":
          description: Return an HTTP 200 status and the word "OK" only to indicate that the data was received successfully

components:
  securitySchemes:
    ApiKey:
      type: apiKey
      in: header
      name: Authorization
      description: >
        Example: `Authorization: App YOUR_API_KEY`

  schemas:
    MessageContentResponse202:
      type: object
      properties:
        response:
          type: object
          properties:
            response_code:
              type: string
              example: "202"
            response_desc:
              type: string
              example: "Request successfully queued."
        details:
          type: string
          example: Request accepted for processing.

    MessageContentResponse400:
      type: object
      properties:
        response:
          type: object
          properties:
            response_code:
              type: string
              example: "400"
            response_desc:
              type: string
              example: "Wrong query syntax or missing mandatory field."
        error:
          type: string
          example: "Missing mandatory phone ID."

    MessageContentResponse403:
      type: object
      properties:
        response:
          type: object
          properties:
            response_code:
              type: string
              example: "403"
            response_desc:
              type: string
              example: "Access to the requested resource has been denied."
        error:
          type: string
          example: "API Key not allowed or account discontinued."

    MessageContentResponse404:
      type: object
      properties:
        response:
          type: object
          properties:
            response_code:
              type: string
              example: "404"
            response_desc:
              type: string
              example: "The requested resource was not found."
        error:
          type: string
          example: "Invalid wabaId value (not found)."

    MessageContentResponse413:
      type: object
      properties:
        response:
          type: object
          properties:
            response_code:
              type: string
              example: "413"
            response_desc:
              type: string
              example: "The request payload exceeds the maximum allowed size."
        error:
          type: string
          example: "Too many recipients (max.: ....)."

    MessageContentResponse503:
      type: object
      properties:
        response:
          type: object
          properties:
            response_code:
              type: string
              example: "503"
            response_desc:
              type: string
              example: "Service temporarily unavailable."
        error:
          type: string
          example: "Authentication failed for unknown reason."
